apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: 1  # Initially running 1 pod
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-container
          image: rohith1305/my-spring-boot-app:latest  # Replace with your Docker Hub image
          ports:
           - containerPort: 8080
