apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  selector:
    app: spring-boot-app
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 8080  # Port inside the container
  type: LoadBalancer  # Use NodePort if running 
